### ISSUE TITLE
Differences with tmux-prefix-highlight

### ISSUE THREAD

**Issue by steakhutzeee** [MunifTanjim/tmux-mode-indicator#12]
Hi, thank you for your plugin.

Out of curiosity, what is the difference between this plugin and https://github.com/tmux-plugins/tmux-prefix-highlight ?

You mentioned this is a trimmed down version of it. Which are the differences? 

Thanks!

**Comment by MunifTanjim** [comment]
> You mentioned this is a trimmed down version of it.

You can check it yourself:

- https://github.com/MunifTanjim/tmux-mode-indicator/blob/master/mode_indicator.tmux
- https://github.com/tmux-plugins/tmux-prefix-highlight/blob/master/prefix_highlight.tmux

> Which are the differences?

The configuration options are different and this one has custom indicator support.

Pick whichever one you like. The end result would be pretty similar.
