### ISSUE TITLE
Issue with bold fonts

### ISSUE THREAD

**Issue by ret2src** [MunifTanjim/tmux-mode-indicator#4]
First of all, thank you very much for developing this tmux plugin! I really like it!

Would it be possible to add proper support for bold fonts?
I know I can use a bold font for one type of indicator by specifying `fg=...,bg=...,bold` as an additional "color parameter". However, when adding `bold` to all types of indicators, weird things happen: The interpretation of `#{tmux_mode_indicator}` gets messed up, see image below.

![image](https://user-images.githubusercontent.com/2010034/135599114-17419dbe-de97-4e3a-add2-959ed6a1804a.png)

Here's the snippet from my configuration:

```
# Visually indicate when prefix is active.
set -g @plugin 'MunifTanjim/tmux-mode-indicator'
set -g @mode_indicator_empty_mode_style 'bg=white,fg=black,bold'
set -g @mode_indicator_copy_mode_style 'bg=yellow,fg=black,bold'
set -g @mode_indicator_prefix_mode_style 'bg=cyan,fg=black,bold'
```

**Comment by MunifTanjim** [comment]
Hey @ret2src,

~Can you try `'bg=cyan,fg=black bold'` and see if that works?~

I just pushed a commit that should fix it 😄 

Thanks for reporting it.

**Comment by ret2src** [comment]
Now that was not only quick but rapid, thank you so much!

Seems to work now 😊
