### ISSUE TITLE
how can I disable an indicator?

### ISSUE THREAD

**Issue by amigthea** [MunifTanjim/tmux-mode-indicator#6]
I want to disable the empty prompt indicator but I wasn't able to with `set -g @mode_indicator_empty_prompt ''`

**Comment by amigthea** [comment]
solved with an empty space `with set -g @mode_indicator_empty_prompt ' '`

**Comment by MunifTanjim** [comment]
You can also use zero-width-space https://unicode-table.com/en/200B/

```sh
set -g @mode_indicator_empty_prompt '​'
```
