### ISSUE TITLE
[Help] tmux-suspend status cannot be displayed properly

### ISSUE THREAD

**Issue by mritd** [MunifTanjim/tmux-mode-indicator#8]
I encountered a strange problem where when I use tmux-suspend, pressing the F12 key does work; however, tmux-mode-indicator cannot display correctly.

This is my `.tmux.conf` that I use, and after testing it, I found some issues.

[tmux.conf](https://github.com/mritd/init/blob/1d930ca270/tmux/tmux.conf)

In order to ensure that every time I use tmux, I enter a "safe environment (local session)", I use a zsh func to enter tmux:

<img width="487" alt="image" src="https://user-images.githubusercontent.com/13043245/227466103-6c0d231f-ae42-4b30-b409-f924055d0034.png">

When I enter tmux in this way, none of the three sessions can display the tmux-suspend status correctly; but when I directly use the `tmux` command (which will automatically create a new session), the tmux-suspend status in this session is displayed normally.

**Comment by mritd** [comment]
If I directly use `@suspend_suspended_options` configuration, it will work normally no matter what; 
I suspect this is due to some variable loading priority issues.

<img width="809" alt="image" src="https://user-images.githubusercontent.com/13043245/227468867-13337a6b-523e-487f-b8eb-c2ce26443a04.png">

**Comment by MunifTanjim** [comment]
Can you check if the latest commit https://github.com/MunifTanjim/tmux-mode-indicator/commit/7027903adca37c54cb8f5fa99fc113b11c23c2c4 fixes it?

**Comment by mritd** [comment]
Thank you very much, everything is working fine now. 😄
